
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int finponderacion = 14;
  public static final int estilo = 18;
  public static final int cuerpos = 6;
  public static final int cadena = 5;
  public static final int estudiante = 7;
  public static final int coma = 27;
  public static final int apellidos = 10;
  public static final int abre = 21;
  public static final int porcentaje = 16;
  public static final int num = 3;
  public static final int valor = 15;
  public static final int abresolo = 26;
  public static final int finestilo = 19;
  public static final int reporte = 17;
  public static final int igual = 24;
  public static final int EOF = 0;
  public static final int id = 4;
  public static final int cuerpostyle = 12;
  public static final int carnet = 8;
  public static final int cierra = 22;
  public static final int finreportes = 20;
  public static final int error = 1;
  public static final int fincuerpos = 11;
  public static final int ponderacion = 13;
  public static final int cierrasolo = 25;
  public static final int nombres = 9;
  public static final int encabezados = 2;
  public static final int dospuntos = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "encabezados",
  "num",
  "id",
  "cadena",
  "cuerpos",
  "estudiante",
  "carnet",
  "nombres",
  "apellidos",
  "fincuerpos",
  "cuerpostyle",
  "ponderacion",
  "finponderacion",
  "valor",
  "porcentaje",
  "reporte",
  "estilo",
  "finestilo",
  "finreportes",
  "abre",
  "cierra",
  "dospuntos",
  "igual",
  "cierrasolo",
  "abresolo",
  "coma"
  };
}

